# Generated by Django 5.1.4 on 2024-12-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
    ]
