# Generated by Django 5.1.4 on 2024-12-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_rename_gallery_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
