# Generated by Django 5.1.4 on 2024-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('wedding', 'Wedding'), ('family', 'Family'), ('event', 'Event'), ('birthday', 'Birthday')], max_length=20),
        ),
    ]
